# Generated by Django 4.0.4 on 2022-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie3', '0003_jobs_description_jobs_how_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='fara descriere'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='how_to_apply',
            field=models.TextField(default='trimite cv la adresa de pe Site'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], max_length=11),
        ),
    ]
